greetings: "Hello! I'm <strong>Pasquale Lisena</strong> and I am a <strong>Web Engineer and Researcher.</strong>"
social:
  - label: twitter
    icon: mdi-twitter
    uri: https://twitter.com/PasqLisena
    top: true
  - label: mail
    icon: mdi-email
    uri: mailto:pasquale.lisena@eurecom.fr
    top: true
    bottom: false
  - label: github
    icon: mdi-github-circle
    uri: https://github.com/pasqLisena
  - label: instagram
    icon: mdi-instagram
    uri: https://www.instagram.com/pasqlisena/
  - label: linkedin
    icon: mdi-linkedin
    uri: https://www.linkedin.com/in/pasqualelisena/
  - label: slideshare
    icon: mdi-file-presentation-box
    uri: https://www.slideshare.net/SquaLeLis
